# Generated by Django 5.1.3 on 2024-12-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WildLife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name of image')),
                ('page_location', models.CharField(max_length=50, verbose_name='Page Where Image is/was Located')),
                ('section', models.CharField(max_length=50, verbose_name='Part of the page where Image is located')),
                ('image_url', models.URLField(max_length=300, null=True, unique=True, verbose_name='link of the image')),
                ('image', models.ImageField(upload_to='wildlife/', verbose_name='Image')),
                ('slug_field', models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='slug field')),
            ],
        ),
    ]
